name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Gradle
      run: |
        # این بخش به صورت خودکار نسخه گریدل را دانلود می‌کند
        ./gradlew --version || (curl -s "https://services.gradle.org/distributions/gradle-8.0-bin.zip" -o gradle-8.0-bin.zip && unzip gradle-8.0-bin.zip && ./gradle-8.0/bin/gradle assembleDebug)
